In [32]:
import numpy as np

In [43]:
read = np.loadtxt('dataset_LP_1.txt',delimiter=',')
np.random.shuffle(read)
labels = read[:,-1]
data = read[:,0:len(read[0])-1]

nclasses = len(np.unique(labels))
nfeatures = len(data[0])
print("No.of Classes = {}".format(nclasses))
print("No.of Features = {}".format(nfeatures))

No.of Classes = 2
No.of Features = 4


In [34]:
train_size = int(len(data)*0.7)
df_train = data[0:train_size]
train_class = labels[0:train_size]
train_class1 = np.reshape(train_class,(len(train_class),1))

df_test  = data[train_size:]
test_class = labels[train_size:]
test_class1 = np.reshape(test_class,(len(test_class),1))
print(df_train)

[[ 2.0007   1.8644   2.6491   0.47369]
 [-1.6029  -0.38903  1.62     1.9103 ]
 [-0.2062   9.2207  -3.7044  -6.8103 ]
 ...
 [-0.38388 -1.0471   8.0514   0.49567]
 [ 1.1558   6.4003   1.5506   0.6961 ]
 [ 3.3004   7.0811  -1.3258   0.22283]]


In [44]:
m, n = df_train.shape
mt, nt = df_test.shape
lr = 0.01
w = np.zeros((nfeatures,1))

In [39]:
def predict(data, weights, bias):
    gx = np.dot(data,weights)+bias
    if(gx>=0):
         return 1
   
    return 0

In [47]:
#fitting w
flag = 1
bias = 0.0
epochs = 1000

for e in range(epochs):    
    count = 0
    
    for i in range(m):
        xi = np.array(df_train[i])
        xi = np.expand_dims(xi, axis=0)

        
        hx = predict(xi,w,bias)

        delta = (train_class1[i] - hx)

        if(delta != 0):
            w = w + lr*delta*(xi.T)
            bias = bias + lr * delta
        else:
            count += 1
           
        acc=count/len(df_train)
        if acc==1.0:
            flag = 0;
            break
    if(flag == 0):
        break

print('Accuracy of training data = %f'%(acc))
print('Weight vector is {}'.format(w))


Accuracy of training data=0.987500
Weight vector is /n[[-2.97248036]
 [-1.621118  ]
 [-1.96497791]
 [-0.34549824]]


In [41]:
#predicting for the test data
y_testp = []
for row in df_test:
    xi = np.array(row)
    xi = np.expand_dims(xi, axis=0)
    y_testp.append(predict(xi,w,bias))


In [42]:
#accuracy of test data
count = 0
for i in range(mt):
    if y_testp[i] == test_class1[i]:
        count = count + 1
accuracy = (count/mt)*100
print("accuracy on test data = ", accuracy)

accuracy on test data =  98.54368932038835
